/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d9d9e5',
        'secondary-fixed-dim': '#c0c7d6',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'inverse-surface': '#2e3039',
        'secondary-container': '#dce2f3',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-secondary-container': '#5e6572',
        'inverse-primary': '#b4c5ff',
        'on-primary-container': '#eeefff',
        'error-container': '#ffdad6',
        'on-background': '#191b23',
        'tertiary-fixed-dim': '#ffb596',
        'secondary': '#585f6c',
        'on-secondary-fixed': '#151c27',
        'on-tertiary-fixed': '#360f00',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container': '#ededf9',
        'inverse-on-surface': '#f0f0fb',
        'surface-variant': '#e1e2ed',
        'primary': '#004ac6',
        'tertiary': '#943700',
        'primary-container': '#2563eb',
        'surface-tint': '#0053db',
        'tertiary-container': '#bc4800',
        'surface-container-high': '#e7e7f3',
        'on-error-container': '#93000a',
        'surface-container-low': '#f3f3fe',
        'outline': '#737686',
        'background': '#faf8ff',
        'surface-container-highest': '#e1e2ed',
        'on-tertiary-container': '#ffede6',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#dce2f3',
        'primary-fixed': '#dbe1ff',
        'on-surface-variant': '#434655',
        'on-surface': '#191b23',
        'tertiary-fixed': '#ffdbcd',
        'on-primary-fixed': '#00174b',
        'surface': '#faf8ff',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'outline-variant': '#c3c6d7',
        'on-secondary-fixed-variant': '#404754',
        'on-error': '#ffffff',
        'surface-bright': '#faf8ff',
        'on-primary-fixed-variant': '#003ea8',
      }
    },
  },
  plugins: [],
}
